name: Publish TestPyPI release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    uses: ./.github/workflows/package.yml

  publish:
    needs: package
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/lumberjack/
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist

      - name: Publish to TestPyPI with Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
